# fly.toml app configuration file generated for replicate-replicare-bot on 2023-04-26T18:24:05+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "replicate-replicare-bot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[build]
  builtin = "node"

[env]

[experimental]
  auto_rollback = true
